spring:
  application:
    name: sueldo-import-system

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/sueldos_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 5
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 3
          multiplier: 2

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8080

# Configuración de Importación
importacion:
  chunk-size: 1000
  max-concurrent-jobs: 10
  temp-directory: ./temp-uploads
  max-errors-per-job: 1000

# Resilience4j
resilience4j:
  retry:
    instances:
      importacionRetry:
        max-attempts: 3
        wait-duration: 3s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - java.sql.SQLException

  circuitbreaker:
    instances:
      importacionCB:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 60s
        permitted-number-of-calls-in-half-open-state: 10
        sliding-window-size: 100
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 60s

  bulkhead:
    instances:
      importacionBulkhead:
        max-concurrent-calls: 10
        max-wait-duration: 0

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.tech.apicargamasiva: DEBUG
    org.springframework.amqp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"